### ISSUE TITLE
Better documentation on how to set it up on Kubernetes

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [discourse/prometheus_exporter#155]
Hi,

we are more or less new to kubernetes and can't get it working somehow, so it would be great if you could tell me how to do it, I would also send a PR afterwards to improve the documentation.

Right now we a kubernetes cluster running, managed with Rancher and have Ruby on Rails running, with a background collector worker, the rails webserver sends it stats to the collector, we can query the collector and also added a service + service monitor - but the results still don't get scraped by prometheus, even though we added the corresponding annotations.

See here:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rails-service-monitor
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: company-prometheus-exporter-service
  endpoints:
  - port: prometheus
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: company-prometheus-exporter-service
  namespace: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9394'
spec:
  selector:
    app: company-prometheus-exporter
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9394
    protocol: TCP
    targetPort: 9394
```

Would be cool if someone has a hint for us, we already spent several hours to get it running and can't figure out whats missing...
