### ISSUE TITLE
Can't seem to get prometheus exporter to export metrics to my Prometheus server in a Kubernetes stack.

### ISSUE THREAD

**Issue by Kosmin** [discourse/prometheus_exporter#164]
First of all thank you for building this awesome project. I used it in a number of past projects, and it worked great! However now I'd like to move towards using kubernetes, and I have a number of exporters set up and grafana. Everything is working.

But when trying to export rails metrics using prometheus_exporter, I can't seem to get any data into my prometheus services/pods. I've tried everything, including creating a separate service & container for the PrometheusExporter web server.

Can you please help me? Any and all answers are highly appreciated!

**Comment by Kosmin** [comment]
Got it running, just adding this in here for anyone who ran into the same issue. I'm a fan of minimalism, so this is they type of answer I was expecting, but if anyone wants details and exact configs, add a comment in here and I'll reply with details.

1. start your rails POD and make sure your `.env` file or your ENV variables are loaded, and add in those env variables the POSTGRES_EXPORTER_HOST and POSTGRES_EXPORTER_PORT set to the name of your k8s service and exposed port

2. create a kubernetes deployment and a service to just run `postgres_exporter` and access it on port 9394. In that deployment, specify the command to also bind to `0.0.0.0`, and your exposed port. Otherwise, it won't work.

3. to test that the exporter is running, check your rails logs that you don't get errors like `connection refused` or `getaddr error: Name not resolved`. If you don't get these errors, it means rails successfully connected to the exporter svc & pod

4. check the logs for the exporter pod - should see something like `Starting prometheus exporter on 0.0.0.0:9394`

5. `k -n <your_namespace> port-forward service/prometheus-rails-exporter 9394:9394`

6. Access `localhost:9394/metrics` and check that you see some metrics in there => success!!

7. In your prometheus deployment config (if you're using [Helm](https://helm.sh/), then in your .values file) add the prometheus-exporter as a scrape target:
```
    - job_name: rails
        scrape_interval: 10s
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - <your-namespace>
        metrics_path: "metrics"
        static_configs:
        - targets:
          - prometheus-rails-exporter:9394
```

** Don't forget to change the namespace to match yours, or remove it if you're not using a namespace **

This took a while, but posting this in there so that everyone using or starting out with k8s knows that this will work. If it doesn't work for you it means you skipped or didn't properly do one of the steps above 👍
